apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-web-app.fullname" . }}
  labels:
    {{- include "python-web-app.labels" . | nindent 4 }}
data:
{{- (.Files.Glob "configs/**").AsConfig | nindent 2 }}
